[build]
  publish = "."

[dev]
  command = "echo 'Dev server not required for static site'"

[[redirects]]
  from = "/api/*"
  to = "https://example.com/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[forms]
  enabled = true
